#
# Copyright (C) 2020 PatrickKR
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Contact me on <mailpatrickkr@gmail.com>
#

name: "Java CI"
on: [ push, pull_request ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Cache Gradle"
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: "Setup Gradle"
        run: chmod +x ./gradlew

      - name: "Gradle Build"
        run: ./gradlew clean publishToMavenLocal

      - name: "Package Version"
        id: version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: "gradle.properties"
          property: "version"

      - name: "Upload Build Output"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ steps.version.outputs.value }}-${{ github.sha }}
          path: |
            ~/.m2/repository/com/github/patrick-mc/${{ github.event.repository.name }}/${{ steps.version.outputs.value }}
            ./LICENSE
            ./README.md


      - name: "Copy Build Output"
        run: |
          cp -r ~/.m2/repository/com/github/patrick-mc/${{ github.event.repository.name }}/${{ steps.version.outputs.value }} ./artifacts
          cp ./LICENSE ./artifacts
          cp ./README.md ./artifacts

      - name: "Upload Test Results"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-test-${{ steps.version.outputs.value }}-${{ github.sha }}
          path: |
            ./build/reports/tests/test

      - name: "Copy JaCoCo Coverage Exec"
        run: cp ./build/jacoco/test.exec ./build/reports/jacoco

      - name: "Upload JaCoCo Results"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-jacoco-${{ steps.version.outputs.value }}-${{ github.sha }}
          path: ./build/reports/jacoco